### ISSUE TITLE
Buildbot cannot start after setting github_token to env:MISSING_VARIABLE

### ISSUE THREAD

**Issue by MarSoft** [buildbot/buildbot_travis#105]
I set `github_token` value for my project to `env:GITHUB_TOKEN`. And I added such variable to `env:` section. Now when I try to start buildbot master, I get the following traceback:
```
2019-03-14 23:05:49+0000 [-] error while parsing config file:
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/usr/local/lib/python3.7/dist-packages/buildbot/config.py", line 173, in loadConfig
            self.basedir, self.configFileName)
        --- <exception caught here> ---
          File "/usr/local/lib/python3.7/dist-packages/buildbot/config.py", line 131, in loadConfigDict
            execfile(filename, localDict)
          File "/usr/lib/python3/dist-packages/twisted/python/compat.py", line 246, in execfile
            exec(code, globals, locals)
          File "/var/lib/buildbot/masters/ci2/master.cfg", line 4, in <module>
            TravisConfigurator(BuildmasterConfig, basedir).fromYaml('cfg.yml')
          File "/usr/local/lib/python3.7/dist-packages/buildbot_travis/configurator.py", line 74, in fromYaml
            return self.fromDict(y)
          File "/usr/local/lib/python3.7/dist-packages/buildbot_travis/configurator.py", line 88, in fromDict
            self.define_travis_builder(**p)
          File "/usr/local/lib/python3.7/dist-packages/buildbot_travis/configurator.py", line 452, in define_travis_builder
            self.config['services'], spawner_name, try_name, codebases)
          File "/usr/local/lib/python3.7/dist-packages/buildbot_travis/vcs/github.py", line 73, in setupReporters
            token = os.environ[token.split(":", 2)[1]]
          File "/usr/lib/python3.7/os.py", line 678, in __getitem__
            raise KeyError(key) from None
        builtins.KeyError: 'GITHUB_TOKEN'
```
Installed package versions:
```
python==3.7
buildbot==2.1.0
buildbot-console-view==2.0.1
buildbot-grid-view==2.0.1
buildbot-travis==0.6.4
buildbot-waterfall-view==2.0.1
buildbot-worker===1.1.1-3ubuntu5
buildbot-www==2.0.1
```

**Comment by MarSoft** [comment]
For me it looks like it tries to find such variable in the variables set in the system before starting buildbot, rather than `env` section in config.
