### ISSUE TITLE
Cannot install from source

### ISSUE THREAD

**Issue by levitte** [buildbot/buildbot_travis#114]
I've seen issues before, but didn't look too closely before now, and am getting back to the same issues, i.e. am seeing this, followed by a screenful of traceback which doesn't really tell me much, except it might or might not be related to https://github.com/buildbot/guanlecoja:

``` console
Running command: /home/levitte/gitwrk/github.com/buildbot_travis/node_modules/.bin/gulp prod --notests
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
```

<details>
<summary>Full dump</summary>

``` console
: ; python3 setup.py install --prefix ~/.local/
/usr/lib/python3/dist-packages/setuptools/dist.py:475: UserWarning: Normalizing '0.6.5-dev10' to '0.6.5.dev10'
  normalized_version,
running install
running bdist_egg
running egg_info
running build_js
Running command: yarn install --pure-lockfile
yarn install v1.19.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
(node:7299) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 7.46s.
Running command: /home/levitte/gitwrk/github.com/buildbot_travis/node_modules/.bin/gulp prod --notests
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/home/levitte/gitwrk/github.com/buildbot_travis/node_modules/guanlecoja/vendors.js:223323:5)
    at require (/home/levitte/gitwrk/github.com/buildbot_travis/node_modules/guanlecoja/vendors.js:223296:12)
    at util.js:25:21
    at req_ (/home/levitte/gitwrk/github.com/buildbot_travis/node_modules/guanlecoja/vendors.js:223323:5)
    at require (/home/levitte/gitwrk/github.com/buildbot_travis/node_modules/guanlecoja/vendors.js:223296:12)
    at fs.js:42:21
    at req_ (/home/levitte/gitwrk/github.com/buildbot_travis/node_modules/guanlecoja/vendors.js:223323:5)
    at Object.req [as require] (/home/levitte/gitwrk/github.com/buildbot_travis/node_modules/guanlecoja/vendors.js:223240:10)
    at Object.859.natives (/home/levitte/gitwrk/github.com/buildbot_travis/node_modules/guanlecoja/vendors.js:114601:37)
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'future'
  File "/home/levitte/.local/lib/python3.7/site-packages/buildbot_pkg.py", line 260, in setup_www_plugin
    **kw)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/levitte/.local/lib/python3.7/site-packages/buildbot_pkg.py", line 247, in run
    self.run_command('build_js')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/levitte/.local/lib/python3.7/site-packages/buildbot_pkg.py", line 221, in run
    subprocess.check_call(command, shell=shell)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/levitte/gitwrk/github.com/buildbot_travis/node_modules/.bin/gulp', 'prod', '--notests']' returned non-zero exit status 1.
```

</details>

**Comment by levitte** [comment]
After a cleanup of my workspace, I came a little further...

``` console
[11:13:50] Finished 'vendors' after 109 μs
[11:13:50] Starting 'templates'...
[11:13:50] Finished 'templates' after 99 μs
[11:13:50] Finished 'fonts' after 38 ms
[11:13:50] Finished 'index' after 36 ms
[11:13:50] Finished 'imgs' after 536 ms
[11:13:50] Finished 'fixtures' after 531 ms
[11:13:51] Finished 'styles' after 927 ms
[11:13:51] gulp-ng-annotate:Error
[11:13:51] app/app.module.coffee: error: couldn't process source due to parse error
Unexpected character '#' (1:0)

/home/levitte/gitwrk/github.com/buildbot_travis/node_modules/guanlecoja/main.js:128
          throw "stopping because of previous error";
          ^
stopping because of previous error
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'future'
  File "/home/levitte/.local/lib/python3.7/site-packages/buildbot_pkg.py", line 260, in setup_www_plugin
    **kw)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/levitte/.local/lib/python3.7/site-packages/buildbot_pkg.py", line 247, in run
    self.run_command('build_js')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/levitte/.local/lib/python3.7/site-packages/buildbot_pkg.py", line 221, in run
    subprocess.check_call(command, shell=shell)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/levitte/gitwrk/github.com/buildbot_travis/node_modules/.bin/gulp', 'prod', '--notests']' returned non-zero exit status 1.
```

Found something about this in https://github.com/Kagami/gulp-ng-annotate/issues/4, so tried to check that file manually:

``` console
: ; ./node_modules/gulp-ng-annotate/node_modules/.bin/ng-annotate -a buildbot_travis/ui/src/app/app.module.coffee 
error: couldn't process source due to parse error
Unexpected character '#' (1:0)
```

Yeah that didn't help much...

**Comment by tardyp** [comment]
should be fixed by https://github.com/buildbot/buildbot_travis/pull/118
