### ISSUE TITLE
AttributeError: module 'buildbot.process.buildstep' has no attribute 'LoggingBuildStep'

### ISSUE THREAD

**Issue by oxr463** [buildbot/buildbot_travis#143]
```
bbtravis create-master master             Traceback (most recent call last):                                                        File "/tmp/venv/bin/bbtravis", line 5, in <module>      from buildbot_travis.cmdline import bbtravis                                          File "/tmp/venv/lib/python3.9/site-packages/buildbot_travis/__init__.py", line 19, in <module>                                                  from .configurator import TravisConfigurator                                          File "/tmp/venv/lib/python3.9/site-packages/buildbot_travis/configurator.py", line 28, in <module>                                              from .steps import TravisSetupSteps, TravisTrigger                                    File "/tmp/venv/lib/python3.9/site-packages/buildbot_travis/steps/__init__.py", line 19, in <module>                                            from .spawner import TravisTrigger                                                    File "/tmp/venv/lib/python3.9/site-packages/buildbot_travis/steps/spawner.py", line 22, in <module>                                             from .base import ConfigurableStepMixin                                               File "/tmp/venv/lib/python3.9/site-packages/buildbot_travis/steps/base.py", line 86, in <module>                                                class ConfigurableStep(buildstep.LoggingBuildStep, ConfigurableStepMixin):            File "/tmp/venv/lib/python3.9/site-packages/twisted/python/deprecate.py", line 475, in __getattribute__                                         value = getattr(state._module, name)                                                AttributeError: module 'buildbot.process.buildstep' has no attribute 'LoggingBuildStep'
```

**Comment by gonewest818** [comment]
I'm just running into this myself. It looks like the pypi package is out of date compared to what's actually here in github.

**Comment by jstacoder** [comment]
so 2 years and no updates on this? does anybody use buildbot anymore?
