### ISSUE TITLE
Python 3 test failure: "builtins.TypeError: must be str, not bytes"

### ISSUE THREAD

**Issue by rodrigc** [buildbot/buildbot_travis#57]
After you merge this fix:

If you try to run the tests on Python 3 you will get

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/crodrigues/buildbot/master/buildbot/process/buildstep.py", line 547, in startStep
    self.results = yield self.run()
  File "/Users/crodrigues/twisted_14/src/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/crodrigues/twisted_14/src/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/crodrigues/buildbot_travis/buildbot_travis/steps/spawner.py", line 43, in run
    self.config = yield self.getStepConfig()
  File "/Users/crodrigues/twisted_14/src/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/crodrigues/twisted_14/src/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/crodrigues/buildbot_travis/buildbot_travis/steps/base.py", line 57, in getStepConfig
    travis_yml = yield self.getFileContentFromWorker(filename, abandonOnFailure=True)
  File "/Users/crodrigues/twisted_14/src/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/crodrigues/twisted_14/src/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/crodrigues/buildbot/master/buildbot/process/buildstep.py", line 874, in runCommand
    res = yield command.run(self, self.remote, self.build.builder.name)
builtins.TypeError: must be str, not bytes

buildbot_travis.tests.test_integration.TravisMaster.test_travis
-------------------------------------------------------------------------------
```

I looked at the failure, and this is coming from inside buildbot inside StringFileWriter:

https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/remotetransfer.py#L184

So, FileWriter is supposed to give the semantics of writing to a file.  This normally means bytes.

It looks like StringFileWriter is being handed *data* which is bytes, and this
is failing to append to *""* which is unicode on Python 3.

What is the correct fix for this?
How did this slip through the buildbot unit tests?

**Comment by rodrigc** [comment]
@tardyp please help

**Comment by tardyp** [comment]
It looks like StringFileWriter is not properly tested, and there is no integration test on it. Looking at it right now
