### ISSUE TITLE
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by wmariuss** [buildbot/buildbot_travis#92]
```
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 0: ordinal not in range(128)
/usr/local/lib/python2.7/site-packages/buildbot/process/buildstep.py:578 in startStep
577                    self._running = True
578                    self.results = yield self.run()
579                finally:
/usr/local/lib/python2.7/site-packages/buildbot_travis/steps/spawner.py:45 in run
44 
45        rv = yield Trigger.run(self)
46        defer.returnValue(rv)
/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py:1418 in _inlineCallbacks
1417            else:
1418                result = g.send(result)
1419        except StopIteration as e:
/usr/local/lib/python2.7/site-packages/buildbot/steps/trigger.py:234 in run
233    def run(self):
234        schedulers_and_props = yield self.getSchedulersAndProperties()
235 
/usr/local/lib/python2.7/site-packages/buildbot_travis/steps/spawner.py:76 in getSchedulersAndProperties
75                str(self.config.label_mapping.get(v, v))
76                for k, v in flat_env.items() if k not in reason_excluded_env)
77            props_to_set.setProperty("virtual_builder_name", u" ".join(tags + label_tags),
/usr/local/lib/python2.7/site-packages/buildbot_travis/steps/spawner.py:76 in <genexpr>
75                str(self.config.label_mapping.get(v, v))
76                for k, v in flat_env.items() if k not in reason_excluded_env)
77            props_to_set.setProperty("virtual_builder_name", u" ".join(tags + label_tags),
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 0: ordinal not in range(128)
```

**Comment by wmariuss** [comment]
Looks like the same in Python >= 3.5
```
buildbot.process.remotecommand.RemoteException: b'exceptions.UnicodeEncodeError': b"'ascii' codec can't encode character u'\\u2014' in position 14: ordinal not in range(128)" b'Traceback (most recent call last):\n File "/usr/local/lib/python2.7/dist-packages/twisted/spread/pb.py", line 1054, in _recvMessage\n netResult = object.remoteMessageReceived(self, message, netArgs, netKw)\n File "/usr/local/lib/python2.7/dist-packages/twisted/spread/flavors.py", line 125, in remoteMessageReceived\n state = method(*args, **kw)\n File "/usr/local/lib/python2.7/dist-packages/buildbot_worker/base.py", line 154, in remote_startCommand\n d = self.command.doStart()\n File "/usr/local/lib/python2.7/dist-packages/buildbot_worker/commands/base.py", line 163, in doStart\n d = defer.maybeDeferred(self.start)\n--- <exception caught here> ---\n File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred\n result = f(*args, **kw)\n File "/usr/local/lib/python2.7/dist-packages/buildbot_worker/commands/shell.py", line 47, in start\n logEnviron=args.get(\'logEnviron\', True),\n File "/usr/local/lib/python2.7/dist-packages/buildbot_worker/runprocess.py", line 334, in __init__\n self.command = to_bytes(util.Obfuscated.get_real(command))\n File "/usr/local/lib/python2.7/dist-packages/buildbot_worker/runprocess.py", line 329, in to_bytes\n cmd[i] = a.encode(self.builder.unicode_encoding)\nexceptions.UnicodeEncodeError: \'ascii\' codec can\'t encode character u\'\\u2014\' in position 14: ordinal not in range(128)\n'
/usr/local/lib/python3.5/site-packages/buildbot/process/buildstep.py:578 in startStep
577                    self._running = True
578                    self.results = yield self.run()
579                finally:
/usr/local/lib/python3.5/site-packages/buildbot_travis/steps/create_steps.py:45 in run
44            command=["bash", "-c", command])
45        yield self.runCommand(cmd)
46        self.setProperty(
/usr/local/lib/python3.5/site-packages/buildbot/process/buildstep.py:901 in runCommand
900        try:
901            res = yield command.run(self, self.remote, self.build.builder.name)
902        finally:
/usr/local/lib/python3.5/site-packages/buildbot/process/remotecommand.py:338 in remoteComplete
337                maybeFailure.type = RemoteException
338            maybeFailure.raiseException()
339 
/usr/local/lib/python3.5/site-packages/twisted/python/failure.py:467 in raiseException
466        def raiseException(self):
467            raise self.value.with_traceback(self.tb)
468    else:
buildbot.process.remotecommand.RemoteException: b'exceptions.UnicodeEncodeError': b"'ascii' codec can't encode character u'\\u2014' in position 14: ordinal not in range(128)" b'Traceback (most recent call last):\n File "/usr/local/lib/python2.7/dist-packages/twisted/spread/pb.py", line 1054, in _recvMessage\n netResult = object.remoteMessageReceived(self, message, netArgs, netKw)\n File "/usr/local/lib/python2.7/dist-packages/twisted/spread/flavors.py", line 125, in remoteMessageReceived\n state = method(*args, **kw)\n File "/usr/local/lib/python2.7/dist-packages/buildbot_worker/base.py", line 154, in remote_startCommand\n d = self.command.doStart()\n File "/usr/local/lib/python2.7/dist-packages/buildbot_worker/commands/base.py", line 163, in doStart\n d = defer.maybeDeferred(self.start)\n--- <exception caught here> ---\n File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred\n result = f(*args, **kw)\n File "/usr/local/lib/python2.7/dist-packages/buildbot_worker/commands/shell.py", line 47, in start\n logEnviron=args.get(\'logEnviron\', True),\n File "/usr/local/lib/python2.7/dist-packages/buildbot_worker/runprocess.py", line 334, in __init__\n self.command = to_bytes(util.Obfuscated.get_real(command))\n File "/usr/local/lib/python2.7/dist-packages/buildbot_worker/runprocess.py", line 329, in to_bytes\n cmd[i] = a.encode(self.builder.unicode_encoding)\nexceptions.UnicodeEncodeError: \'ascii\' codec can\'t encode character u\'\\u2014\' in position 14: ordinal not in range(128)\n'
```

**Comment by wmariuss** [comment]
`[["Python","3.5.6"],["Buildbot","1.5.0"],["Twisted","18.9.0"],["buildbot_travis","0.6.3"],["buildbot-grid-view","1.5.0"]]`

**Comment by wmariuss** [comment]
Resolved.

Instead this:
```
language: python
python:
  — "2.7"

install:
  - echo yes
```
 use like this:

```
language: python
python:
  — 2.7

install:
  - echo yes
```
